### ISSUE TITLE
Tutorial request!

### ISSUE THREAD

**Issue by croxis** [Kehom/gdDedicatedServer#1]
First, thank you for the Addon library and these tutorials. Writing good tutorials like this is a LOT of work and I greatly appreciate the time you have spent on it.

I have a feature/tutorial request. Many single player games are actually running a server internally, just only accepting localhost connections. Opening up the game for multiplayer is a quick toggle. I would love to learn how to do that, with your addon library and the current dedicated server framework.

Another request, but this is a bit out of scope, is setting up the dedicated server for a headless/console only machine with some sort of text or ncurses prompt (like minecraft server).

**Comment by Kehom** [comment]
> First, thank you for the Addon library and these tutorials. Writing good tutorials like this is a LOT of work and I greatly appreciate the time you have spent on it.

Thank you! That encourages me a lot to continue working on the web page!

> I have a feature/tutorial request. Many single player games are actually running a server internally, just only accepting localhost connections. Opening up the game for multiplayer is a quick toggle. I would love to learn how to do that, with your addon library and the current dedicated server framework.

OK. "Out of the box" the Networking Addon does not exactly allow this kind of behavior, of being able to start a server when the simulation is already going on. Well, sort of. If you look into the demo project you will see that it allows one to start the game in single player, where the server is not started. However you can actually start the server following the exact same logic of the multiplayer hosting but with an additional line right before transitioning into the game scene:

```
get_tree().set_refuse_new_network_connections(true)
```

In this case the server is on but no one will be able to connect into it. As part of the game logic you can even allow the game to pause since only the server/authoritative machine is running. Then, whenever desired you can then set that flag to false in order to allow other peers to connect. In theory this should work on both supported modes (ENet and WebSocket).

> Another request, but this is a bit out of scope, is setting up the dedicated server for a headless/console only machine with some sort of text or ncurses prompt (like minecraft server).

I did start to look into something like that but I still need to perform a lot of research. The thing is, I'm not exactly sure how to start a Godot Project that will actually open a console window allowing input commands to be entered. Another possibility here would be to create a "management client" with special privileges to connect into the server. This obviously would require a proper credential system to be incorporated.

**Comment by croxis** [comment]
> 
> Thank you! That encourages me a lot to continue working on the web page!
> 

I'm a high school teacher, so I have a lot of empathy in that department!

> 
>  However you can actually start the server following the exact same logic of the multiplayer hosting but with an additional line right before transitioning into the game scene:
> 
> ```
> get_tree().set_refuse_new_network_connections(true)
> ```
> 
> In this case the server is on but no one will be able to connect into it. As part of the game logic you can even allow the game to pause since only the server/authoritative machine is running. Then, whenever desired you can then set that flag to false in order to allow other peers to connect. In theory this should work on both supported modes (ENet and WebSocket).
> 

That is exactly what I was looking for, thank you.

> I did start to look into something like that but I still need to perform a lot of research. The thing is, I'm not exactly sure how to start a Godot Project that will actually open a console window allowing input commands to be entered. Another possibility here would be to create a "management client" with special privileges to connect into the server. This obviously would require a proper credential system to be incorporated.

I know there is a server version of the godot binary for linux and osx for headless systems, and it is being better abstracted for 4.0. I haven't tried it yet myself. This is a way-down-the-road thing for me. I am just happy I have a mostly-working prototype at this point!  Linux and BSD are the only systems that are ran truly headless -- so either a more generic management client and/or a linux specific wrapper with a fancy ncurses interface.
